import { useEffect, useRef, useState } from 'react'
import styles from './LeafletListingMap.module.css'
interface MapApi { setView(center:[number,number],zoom:number):MapApi; remove():void; invalidateSize():void }
interface MarkerApi { addTo(map:MapApi):MarkerApi; bindPopup(content:string):MarkerApi }
interface LeafletApi { map(el:HTMLElement, options?:Record<string,unknown>):MapApi; tileLayer(url:string, options:Record<string,unknown>):{addTo(map:MapApi):void}; circleMarker(point:[number,number],options:Record<string,unknown>):MarkerApi }
const css='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'; const script='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'; let pending:Promise<LeafletApi>|undefined
function load():Promise<LeafletApi>{const leaflet=(window as Window & { L?: LeafletApi }).L;if(leaflet)return Promise.resolve(leaflet);if(pending)return pending;pending=new Promise((resolve,reject)=>{if(!document.querySelector(`link[href="${css}"]`)){const link=document.createElement('link');link.rel='stylesheet';link.href=css;document.head.appendChild(link)}const tag=document.createElement('script');tag.src=script;tag.async=true;tag.onload=()=>{const loaded=(window as Window & { L?: LeafletApi }).L; loaded?resolve(loaded):reject(new Error('Leaflet yüklenemedi'))};tag.onerror=()=>reject(new Error('Leaflet yüklenemedi'));document.head.appendChild(tag)});return pending}
export interface LeafletListingPoint { id:string; lat:number; lng:number; label:string; popup:string }
export function LeafletListingMap({points,onSelect}:{points:LeafletListingPoint[];onSelect?(id:string):void}){const root=useRef<HTMLDivElement>(null);const map=useRef<MapApi | undefined>(undefined);const [error,setError]=useState(false);useEffect(()=>{let disposed=false;void load().then((L)=>{if(disposed||!root.current)return;const instance=L.map(root.current,{zoomControl:true,scrollWheelZoom:true}).setView([39,35.2],5.5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(instance);map.current=instance;points.forEach((point)=>L.circleMarker([point.lat,point.lng],{radius:10,color:'var(--lg-accent)',fillColor:'var(--lg-accent)',fillOpacity:.9,weight:2}).bindPopup(point.popup).addTo(instance));setTimeout(()=>instance.invalidateSize(),0)}).catch(()=>{if(!disposed)setError(true)});return()=>{disposed=true;map.current?.remove();map.current=undefined}},[points]);return <div className={styles.root}><div ref={root} className={styles.map} aria-label="OpenStreetMap arsa ilanları haritası"/>{error?<div className={styles.error}>Harita yüklenemedi.</div>:null}<span className={styles.credit}>OpenStreetMap · Leaflet</span></div>}
