/**
 * Türkiye il listesi (plaka sırasıyla).
 *
 * İl SERBEST METİN olamaz: ofis kaydı ilan aramasının il filtresini besler ve
 * "İzmir" / "izmir" / "İZMİR" üç ayrı değer olarak kaydedilirse filtre
 * sessizce eksik sonuç döndürür. Bu yüzden kurumsal başvuruda il bir
 * `<select>`'tir ve doğrulama değeri bu listeye karşı sınar.
 *
 * İlçe hâlâ metindir: 970+ ilçenin ile bağlı listesi bu akışın kapsamı
 * dışında; ilçe veri kümesi geldiğinde burası da bağımlı select'e döner.
 */
export const ILLER: readonly string[] = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Amasya',
  'Ankara',
  'Antalya',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkâri',
  'Hatay',
  'Isparta',
  'Mersin',
  'İstanbul',
  'İzmir',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırklareli',
  'Kırşehir',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Kahramanmaraş',
  'Mardin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Şanlıurfa',
  'Uşak',
  'Van',
  'Yozgat',
  'Zonguldak',
  'Aksaray',
  'Bayburt',
  'Karaman',
  'Kırıkkale',
  'Batman',
  'Şırnak',
  'Bartın',
  'Ardahan',
  'Iğdır',
  'Yalova',
  'Karabük',
  'Kilis',
  'Osmaniye',
  'Düzce',
]

/** Verilen değer listede var mı — doğrulama bunu tüketir. */
export function ilGecerliMi(ham: string): boolean {
  return ILLER.includes(ham.trim())
}
