import { REGION_VIEWS, type RegionSearchState, type RegionIntent, type RegionView } from './region-types'

export const DEFAULT_REGION_SEARCH_STATE: RegionSearchState = { query: '', intent: 'invest', view: 'workspace' }
type Raw = Record<string, unknown> | URLSearchParams

function params(raw: Raw) { if (raw instanceof URLSearchParams) return raw; const p = new URLSearchParams(); Object.entries(raw).forEach(([k,v]) => { if (typeof v === 'string' || typeof v === 'number') p.set(k, String(v)) }); return p }
function text(p: URLSearchParams, key: string) { const value = p.get(key)?.trim(); return value || undefined }
function positive(p: URLSearchParams, key: string) { const n = Number(text(p, key)); return Number.isFinite(n) && n > 0 ? n : undefined }
export function parseRegionSearch(raw: Raw): RegionSearchState { const p = params(raw); const intent = text(p, 'intent'); const view = text(p, 'view'); return { query: text(p, 'q') ?? '', intent: ['buy','rent','invest','live'].includes(intent ?? '') ? intent as RegionIntent : 'invest', propertyType: ['land','residential','commercial'].includes(text(p, 'propertyType') ?? '') ? text(p, 'propertyType') as RegionSearchState['propertyType'] : undefined, city: text(p, 'city'), district: text(p, 'district'), neighborhood: text(p, 'neighborhood'), minPrice: positive(p, 'min'), maxPrice: positive(p, 'max'), view: REGION_VIEWS.includes(view as RegionView) ? view as RegionView : 'workspace' } }
export function serializeRegionSearch(state: RegionSearchState): Record<string, string | number> { const p = new URLSearchParams(); if (state.query) p.set('q', state.query); if (state.intent !== 'invest') p.set('intent', state.intent); if (state.propertyType) p.set('propertyType', state.propertyType); if (state.city) p.set('city', state.city); if (state.district) p.set('district', state.district); if (state.neighborhood) p.set('neighborhood', state.neighborhood); if (state.minPrice) p.set('min', String(state.minPrice)); if (state.maxPrice) p.set('max', String(state.maxPrice)); if (state.view !== 'workspace') p.set('view', state.view); return Array.from(p.entries()).reduce<Record<string,string|number>>((a,[k,v]) => { a[k] = ['min','max'].includes(k) ? Number(v) : v; return a }, {}) }
