/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDanismanRouteImport } from './routes/ai-danisman'
import { Route as ArsaAraRouteImport } from './routes/arsa-ara'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BolgelerRouteImport } from './routes/bolgeler'
import { Route as EPostaDogrulaRouteImport } from './routes/e-posta-dogrula'
import { Route as EmlakRouteImport } from './routes/emlak'
import { Route as FavorilerRouteImport } from './routes/favoriler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HesabimRouteImport } from './routes/hesabim'
import { Route as IlanVerRouteImport } from './routes/ilan-ver'
import { Route as KarsilastirRouteImport } from './routes/karsilastir'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as OfislerRouteImport } from './routes/ofisler'
import { Route as OrganizasyonSecRouteImport } from './routes/organizasyon-sec'
import { Route as OturumSuresiDolduRouteImport } from './routes/oturum-suresi-doldu'
import { Route as PaketlerRouteImport } from './routes/paketler'
import { Route as ParolaDegistirRouteImport } from './routes/parola-degistir'
import { Route as ParolaSifirlaRouteImport } from './routes/parola-sifirla'
import { Route as YetkisizRouteImport } from './routes/yetkisiz'
import { Route as DavetTokenRouteImport } from './routes/davet.$token'
import { Route as DavetGecersizRouteImport } from './routes/davet.gecersiz'
import { Route as EmlakEndeksiIndexRouteImport } from './routes/emlak-endeksi.index'
import { Route as EmlakEndeksiSplatRouteImport } from './routes/emlak-endeksi.$'
import { Route as GirisHataRouteImport } from './routes/giris_.hata'
import { Route as GirisKodRouteImport } from './routes/giris_.kod'
import { Route as GirisParolaRouteImport } from './routes/giris_.parola'
import { Route as HesabimIndexRouteImport } from './routes/hesabim.index'
import { Route as HesabimFaturalarimRouteImport } from './routes/hesabim.faturalarim'
import { Route as HesabimGuvenlikRouteImport } from './routes/hesabim.guvenlik'
import { Route as HesabimHareketlerRouteImport } from './routes/hesabim.hareketler'
import { Route as HesabimIlanlarimRouteImport } from './routes/hesabim.ilanlarim'
import { Route as HesabimKayitliAramaRouteImport } from './routes/hesabim.kayitli-arama'
import { Route as HesabimMesajlarRouteImport } from './routes/hesabim.mesajlar'
import { Route as HesabimOdemelerRouteImport } from './routes/hesabim.odemeler'
import { Route as HesabimPlanimRouteImport } from './routes/hesabim.planim'
import { Route as HesabimRandevularimRouteImport } from './routes/hesabim.randevularim'
import { Route as HesapAskidaRouteImport } from './routes/hesap.askida'
import { Route as HesapDogrulaRouteImport } from './routes/hesap.dogrula'
import { Route as IlanListingIdRouteImport } from './routes/ilan.$listingId'
import { Route as KayitHesapVarRouteImport } from './routes/kayit_.hesap-var'
import { Route as KayitKurumsalRouteImport } from './routes/kayit_.kurumsal'
import { Route as KayitProfilRouteImport } from './routes/kayit_.profil'
import { Route as ParolaSifirlaGecersizRouteImport } from './routes/parola-sifirla_.gecersiz'
import { Route as ParolaSifirlaGonderildiRouteImport } from './routes/parola-sifirla_.gonderildi'
import { Route as ParolaSifirlaTamamRouteImport } from './routes/parola-sifirla_.tamam'
import { Route as ParolaSifirlaYeniRouteImport } from './routes/parola-sifirla_.yeni'
import { Route as GirisGoogleCallbackRouteImport } from './routes/giris_.google_.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDanismanRoute = AiDanismanRouteImport.update({
  id: '/ai-danisman',
  path: '/ai-danisman',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsaAraRoute = ArsaAraRouteImport.update({
  id: '/arsa-ara',
  path: '/arsa-ara',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BolgelerRoute = BolgelerRouteImport.update({
  id: '/bolgeler',
  path: '/bolgeler',
  getParentRoute: () => rootRouteImport,
} as any)
const EPostaDogrulaRoute = EPostaDogrulaRouteImport.update({
  id: '/e-posta-dogrula',
  path: '/e-posta-dogrula',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakRoute = EmlakRouteImport.update({
  id: '/emlak',
  path: '/emlak',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorilerRoute = FavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimRoute = HesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanVerRoute = IlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const KarsilastirRoute = KarsilastirRouteImport.update({
  id: '/karsilastir',
  path: '/karsilastir',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const OfislerRoute = OfislerRouteImport.update({
  id: '/ofisler',
  path: '/ofisler',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizasyonSecRoute = OrganizasyonSecRouteImport.update({
  id: '/organizasyon-sec',
  path: '/organizasyon-sec',
  getParentRoute: () => rootRouteImport,
} as any)
const OturumSuresiDolduRoute = OturumSuresiDolduRouteImport.update({
  id: '/oturum-suresi-doldu',
  path: '/oturum-suresi-doldu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaketlerRoute = PaketlerRouteImport.update({
  id: '/paketler',
  path: '/paketler',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaDegistirRoute = ParolaDegistirRouteImport.update({
  id: '/parola-degistir',
  path: '/parola-degistir',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaSifirlaRoute = ParolaSifirlaRouteImport.update({
  id: '/parola-sifirla',
  path: '/parola-sifirla',
  getParentRoute: () => rootRouteImport,
} as any)
const YetkisizRoute = YetkisizRouteImport.update({
  id: '/yetkisiz',
  path: '/yetkisiz',
  getParentRoute: () => rootRouteImport,
} as any)
const DavetTokenRoute = DavetTokenRouteImport.update({
  id: '/davet/$token',
  path: '/davet/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DavetGecersizRoute = DavetGecersizRouteImport.update({
  id: '/davet/gecersiz',
  path: '/davet/gecersiz',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakEndeksiIndexRoute = EmlakEndeksiIndexRouteImport.update({
  id: '/emlak-endeksi/',
  path: '/emlak-endeksi/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakEndeksiSplatRoute = EmlakEndeksiSplatRouteImport.update({
  id: '/emlak-endeksi/$',
  path: '/emlak-endeksi/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisHataRoute = GirisHataRouteImport.update({
  id: '/giris_/hata',
  path: '/giris/hata',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisKodRoute = GirisKodRouteImport.update({
  id: '/giris_/kod',
  path: '/giris/kod',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisParolaRoute = GirisParolaRouteImport.update({
  id: '/giris_/parola',
  path: '/giris/parola',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimIndexRoute = HesabimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimFaturalarimRoute = HesabimFaturalarimRouteImport.update({
  id: '/faturalarim',
  path: '/faturalarim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimGuvenlikRoute = HesabimGuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimHareketlerRoute = HesabimHareketlerRouteImport.update({
  id: '/hareketler',
  path: '/hareketler',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimIlanlarimRoute = HesabimIlanlarimRouteImport.update({
  id: '/ilanlarim',
  path: '/ilanlarim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimKayitliAramaRoute = HesabimKayitliAramaRouteImport.update({
  id: '/kayitli-arama',
  path: '/kayitli-arama',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimMesajlarRoute = HesabimMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimOdemelerRoute = HesabimOdemelerRouteImport.update({
  id: '/odemeler',
  path: '/odemeler',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimPlanimRoute = HesabimPlanimRouteImport.update({
  id: '/planim',
  path: '/planim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimRandevularimRoute = HesabimRandevularimRouteImport.update({
  id: '/randevularim',
  path: '/randevularim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesapAskidaRoute = HesapAskidaRouteImport.update({
  id: '/hesap/askida',
  path: '/hesap/askida',
  getParentRoute: () => rootRouteImport,
} as any)
const HesapDogrulaRoute = HesapDogrulaRouteImport.update({
  id: '/hesap/dogrula',
  path: '/hesap/dogrula',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanListingIdRoute = IlanListingIdRouteImport.update({
  id: '/ilan/$listingId',
  path: '/ilan/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitHesapVarRoute = KayitHesapVarRouteImport.update({
  id: '/kayit_/hesap-var',
  path: '/kayit/hesap-var',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitKurumsalRoute = KayitKurumsalRouteImport.update({
  id: '/kayit_/kurumsal',
  path: '/kayit/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitProfilRoute = KayitProfilRouteImport.update({
  id: '/kayit_/profil',
  path: '/kayit/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaSifirlaGecersizRoute = ParolaSifirlaGecersizRouteImport.update({
  id: '/parola-sifirla_/gecersiz',
  path: '/parola-sifirla/gecersiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaSifirlaGonderildiRoute = ParolaSifirlaGonderildiRouteImport.update({
  id: '/parola-sifirla_/gonderildi',
  path: '/parola-sifirla/gonderildi',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaSifirlaTamamRoute = ParolaSifirlaTamamRouteImport.update({
  id: '/parola-sifirla_/tamam',
  path: '/parola-sifirla/tamam',
  getParentRoute: () => rootRouteImport,
} as any)
const ParolaSifirlaYeniRoute = ParolaSifirlaYeniRouteImport.update({
  id: '/parola-sifirla_/yeni',
  path: '/parola-sifirla/yeni',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisGoogleCallbackRoute = GirisGoogleCallbackRouteImport.update({
  id: '/giris_/google_/callback',
  path: '/giris/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/e-posta-dogrula': typeof EPostaDogrulaRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRouteWithChildren
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/organizasyon-sec': typeof OrganizasyonSecRoute
  '/oturum-suresi-doldu': typeof OturumSuresiDolduRoute
  '/paketler': typeof PaketlerRoute
  '/parola-degistir': typeof ParolaDegistirRoute
  '/parola-sifirla': typeof ParolaSifirlaRoute
  '/yetkisiz': typeof YetkisizRoute
  '/davet/$token': typeof DavetTokenRoute
  '/davet/gecersiz': typeof DavetGecersizRoute
  '/emlak-endeksi/$': typeof EmlakEndeksiSplatRoute
  '/giris/hata': typeof GirisHataRoute
  '/giris/kod': typeof GirisKodRoute
  '/giris/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesabim/planim': typeof HesabimPlanimRoute
  '/hesabim/randevularim': typeof HesabimRandevularimRoute
  '/hesap/askida': typeof HesapAskidaRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit/hesap-var': typeof KayitHesapVarRoute
  '/kayit/kurumsal': typeof KayitKurumsalRoute
  '/kayit/profil': typeof KayitProfilRoute
  '/parola-sifirla/gecersiz': typeof ParolaSifirlaGecersizRoute
  '/parola-sifirla/gonderildi': typeof ParolaSifirlaGonderildiRoute
  '/parola-sifirla/tamam': typeof ParolaSifirlaTamamRoute
  '/parola-sifirla/yeni': typeof ParolaSifirlaYeniRoute
  '/emlak-endeksi/': typeof EmlakEndeksiIndexRoute
  '/hesabim/': typeof HesabimIndexRoute
  '/giris/google/callback': typeof GirisGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/e-posta-dogrula': typeof EPostaDogrulaRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/organizasyon-sec': typeof OrganizasyonSecRoute
  '/oturum-suresi-doldu': typeof OturumSuresiDolduRoute
  '/paketler': typeof PaketlerRoute
  '/parola-degistir': typeof ParolaDegistirRoute
  '/parola-sifirla': typeof ParolaSifirlaRoute
  '/yetkisiz': typeof YetkisizRoute
  '/davet/$token': typeof DavetTokenRoute
  '/davet/gecersiz': typeof DavetGecersizRoute
  '/emlak-endeksi/$': typeof EmlakEndeksiSplatRoute
  '/giris/hata': typeof GirisHataRoute
  '/giris/kod': typeof GirisKodRoute
  '/giris/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesabim/planim': typeof HesabimPlanimRoute
  '/hesabim/randevularim': typeof HesabimRandevularimRoute
  '/hesap/askida': typeof HesapAskidaRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit/hesap-var': typeof KayitHesapVarRoute
  '/kayit/kurumsal': typeof KayitKurumsalRoute
  '/kayit/profil': typeof KayitProfilRoute
  '/parola-sifirla/gecersiz': typeof ParolaSifirlaGecersizRoute
  '/parola-sifirla/gonderildi': typeof ParolaSifirlaGonderildiRoute
  '/parola-sifirla/tamam': typeof ParolaSifirlaTamamRoute
  '/parola-sifirla/yeni': typeof ParolaSifirlaYeniRoute
  '/emlak-endeksi': typeof EmlakEndeksiIndexRoute
  '/hesabim': typeof HesabimIndexRoute
  '/giris/google/callback': typeof GirisGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/e-posta-dogrula': typeof EPostaDogrulaRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRouteWithChildren
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/organizasyon-sec': typeof OrganizasyonSecRoute
  '/oturum-suresi-doldu': typeof OturumSuresiDolduRoute
  '/paketler': typeof PaketlerRoute
  '/parola-degistir': typeof ParolaDegistirRoute
  '/parola-sifirla': typeof ParolaSifirlaRoute
  '/yetkisiz': typeof YetkisizRoute
  '/davet/$token': typeof DavetTokenRoute
  '/davet/gecersiz': typeof DavetGecersizRoute
  '/emlak-endeksi/$': typeof EmlakEndeksiSplatRoute
  '/giris_/hata': typeof GirisHataRoute
  '/giris_/kod': typeof GirisKodRoute
  '/giris_/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesabim/planim': typeof HesabimPlanimRoute
  '/hesabim/randevularim': typeof HesabimRandevularimRoute
  '/hesap/askida': typeof HesapAskidaRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit_/hesap-var': typeof KayitHesapVarRoute
  '/kayit_/kurumsal': typeof KayitKurumsalRoute
  '/kayit_/profil': typeof KayitProfilRoute
  '/parola-sifirla_/gecersiz': typeof ParolaSifirlaGecersizRoute
  '/parola-sifirla_/gonderildi': typeof ParolaSifirlaGonderildiRoute
  '/parola-sifirla_/tamam': typeof ParolaSifirlaTamamRoute
  '/parola-sifirla_/yeni': typeof ParolaSifirlaYeniRoute
  '/emlak-endeksi/': typeof EmlakEndeksiIndexRoute
  '/hesabim/': typeof HesabimIndexRoute
  '/giris_/google_/callback': typeof GirisGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/e-posta-dogrula'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/organizasyon-sec'
    | '/oturum-suresi-doldu'
    | '/paketler'
    | '/parola-degistir'
    | '/parola-sifirla'
    | '/yetkisiz'
    | '/davet/$token'
    | '/davet/gecersiz'
    | '/emlak-endeksi/$'
    | '/giris/hata'
    | '/giris/kod'
    | '/giris/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesabim/planim'
    | '/hesabim/randevularim'
    | '/hesap/askida'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit/hesap-var'
    | '/kayit/kurumsal'
    | '/kayit/profil'
    | '/parola-sifirla/gecersiz'
    | '/parola-sifirla/gonderildi'
    | '/parola-sifirla/tamam'
    | '/parola-sifirla/yeni'
    | '/emlak-endeksi/'
    | '/hesabim/'
    | '/giris/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/e-posta-dogrula'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/organizasyon-sec'
    | '/oturum-suresi-doldu'
    | '/paketler'
    | '/parola-degistir'
    | '/parola-sifirla'
    | '/yetkisiz'
    | '/davet/$token'
    | '/davet/gecersiz'
    | '/emlak-endeksi/$'
    | '/giris/hata'
    | '/giris/kod'
    | '/giris/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesabim/planim'
    | '/hesabim/randevularim'
    | '/hesap/askida'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit/hesap-var'
    | '/kayit/kurumsal'
    | '/kayit/profil'
    | '/parola-sifirla/gecersiz'
    | '/parola-sifirla/gonderildi'
    | '/parola-sifirla/tamam'
    | '/parola-sifirla/yeni'
    | '/emlak-endeksi'
    | '/hesabim'
    | '/giris/google/callback'
  id:
    | '__root__'
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/e-posta-dogrula'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/organizasyon-sec'
    | '/oturum-suresi-doldu'
    | '/paketler'
    | '/parola-degistir'
    | '/parola-sifirla'
    | '/yetkisiz'
    | '/davet/$token'
    | '/davet/gecersiz'
    | '/emlak-endeksi/$'
    | '/giris_/hata'
    | '/giris_/kod'
    | '/giris_/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesabim/planim'
    | '/hesabim/randevularim'
    | '/hesap/askida'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit_/hesap-var'
    | '/kayit_/kurumsal'
    | '/kayit_/profil'
    | '/parola-sifirla_/gecersiz'
    | '/parola-sifirla_/gonderildi'
    | '/parola-sifirla_/tamam'
    | '/parola-sifirla_/yeni'
    | '/emlak-endeksi/'
    | '/hesabim/'
    | '/giris_/google_/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDanismanRoute: typeof AiDanismanRoute
  ArsaAraRoute: typeof ArsaAraRoute
  BlogRoute: typeof BlogRoute
  BolgelerRoute: typeof BolgelerRoute
  EPostaDogrulaRoute: typeof EPostaDogrulaRoute
  EmlakRoute: typeof EmlakRoute
  FavorilerRoute: typeof FavorilerRoute
  GirisRoute: typeof GirisRoute
  HealthRoute: typeof HealthRoute
  HesabimRoute: typeof HesabimRouteWithChildren
  IlanVerRoute: typeof IlanVerRoute
  KarsilastirRoute: typeof KarsilastirRoute
  KayitRoute: typeof KayitRoute
  OfislerRoute: typeof OfislerRoute
  OrganizasyonSecRoute: typeof OrganizasyonSecRoute
  OturumSuresiDolduRoute: typeof OturumSuresiDolduRoute
  PaketlerRoute: typeof PaketlerRoute
  ParolaDegistirRoute: typeof ParolaDegistirRoute
  ParolaSifirlaRoute: typeof ParolaSifirlaRoute
  YetkisizRoute: typeof YetkisizRoute
  DavetTokenRoute: typeof DavetTokenRoute
  DavetGecersizRoute: typeof DavetGecersizRoute
  EmlakEndeksiSplatRoute: typeof EmlakEndeksiSplatRoute
  GirisHataRoute: typeof GirisHataRoute
  GirisKodRoute: typeof GirisKodRoute
  GirisParolaRoute: typeof GirisParolaRoute
  HesapAskidaRoute: typeof HesapAskidaRoute
  HesapDogrulaRoute: typeof HesapDogrulaRoute
  IlanListingIdRoute: typeof IlanListingIdRoute
  KayitHesapVarRoute: typeof KayitHesapVarRoute
  KayitKurumsalRoute: typeof KayitKurumsalRoute
  KayitProfilRoute: typeof KayitProfilRoute
  ParolaSifirlaGecersizRoute: typeof ParolaSifirlaGecersizRoute
  ParolaSifirlaGonderildiRoute: typeof ParolaSifirlaGonderildiRoute
  ParolaSifirlaTamamRoute: typeof ParolaSifirlaTamamRoute
  ParolaSifirlaYeniRoute: typeof ParolaSifirlaYeniRoute
  EmlakEndeksiIndexRoute: typeof EmlakEndeksiIndexRoute
  GirisGoogleCallbackRoute: typeof GirisGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-danisman': {
      id: '/ai-danisman'
      path: '/ai-danisman'
      fullPath: '/ai-danisman'
      preLoaderRoute: typeof AiDanismanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsa-ara': {
      id: '/arsa-ara'
      path: '/arsa-ara'
      fullPath: '/arsa-ara'
      preLoaderRoute: typeof ArsaAraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolgeler': {
      id: '/bolgeler'
      path: '/bolgeler'
      fullPath: '/bolgeler'
      preLoaderRoute: typeof BolgelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-posta-dogrula': {
      id: '/e-posta-dogrula'
      path: '/e-posta-dogrula'
      fullPath: '/e-posta-dogrula'
      preLoaderRoute: typeof EPostaDogrulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak': {
      id: '/emlak'
      path: '/emlak'
      fullPath: '/emlak'
      preLoaderRoute: typeof EmlakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriler': {
      id: '/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof FavorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim': {
      id: '/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof HesabimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan-ver': {
      id: '/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof IlanVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karsilastir': {
      id: '/karsilastir'
      path: '/karsilastir'
      fullPath: '/karsilastir'
      preLoaderRoute: typeof KarsilastirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofisler': {
      id: '/ofisler'
      path: '/ofisler'
      fullPath: '/ofisler'
      preLoaderRoute: typeof OfislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizasyon-sec': {
      id: '/organizasyon-sec'
      path: '/organizasyon-sec'
      fullPath: '/organizasyon-sec'
      preLoaderRoute: typeof OrganizasyonSecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oturum-suresi-doldu': {
      id: '/oturum-suresi-doldu'
      path: '/oturum-suresi-doldu'
      fullPath: '/oturum-suresi-doldu'
      preLoaderRoute: typeof OturumSuresiDolduRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paketler': {
      id: '/paketler'
      path: '/paketler'
      fullPath: '/paketler'
      preLoaderRoute: typeof PaketlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-degistir': {
      id: '/parola-degistir'
      path: '/parola-degistir'
      fullPath: '/parola-degistir'
      preLoaderRoute: typeof ParolaDegistirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-sifirla': {
      id: '/parola-sifirla'
      path: '/parola-sifirla'
      fullPath: '/parola-sifirla'
      preLoaderRoute: typeof ParolaSifirlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yetkisiz': {
      id: '/yetkisiz'
      path: '/yetkisiz'
      fullPath: '/yetkisiz'
      preLoaderRoute: typeof YetkisizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davet/$token': {
      id: '/davet/$token'
      path: '/davet/$token'
      fullPath: '/davet/$token'
      preLoaderRoute: typeof DavetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davet/gecersiz': {
      id: '/davet/gecersiz'
      path: '/davet/gecersiz'
      fullPath: '/davet/gecersiz'
      preLoaderRoute: typeof DavetGecersizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak-endeksi/': {
      id: '/emlak-endeksi/'
      path: '/emlak-endeksi'
      fullPath: '/emlak-endeksi/'
      preLoaderRoute: typeof EmlakEndeksiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak-endeksi/$': {
      id: '/emlak-endeksi/$'
      path: '/emlak-endeksi/$'
      fullPath: '/emlak-endeksi/$'
      preLoaderRoute: typeof EmlakEndeksiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/hata': {
      id: '/giris_/hata'
      path: '/giris/hata'
      fullPath: '/giris/hata'
      preLoaderRoute: typeof GirisHataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/kod': {
      id: '/giris_/kod'
      path: '/giris/kod'
      fullPath: '/giris/kod'
      preLoaderRoute: typeof GirisKodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/parola': {
      id: '/giris_/parola'
      path: '/giris/parola'
      fullPath: '/giris/parola'
      preLoaderRoute: typeof GirisParolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim/': {
      id: '/hesabim/'
      path: '/'
      fullPath: '/hesabim/'
      preLoaderRoute: typeof HesabimIndexRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/faturalarim': {
      id: '/hesabim/faturalarim'
      path: '/faturalarim'
      fullPath: '/hesabim/faturalarim'
      preLoaderRoute: typeof HesabimFaturalarimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/guvenlik': {
      id: '/hesabim/guvenlik'
      path: '/guvenlik'
      fullPath: '/hesabim/guvenlik'
      preLoaderRoute: typeof HesabimGuvenlikRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/hareketler': {
      id: '/hesabim/hareketler'
      path: '/hareketler'
      fullPath: '/hesabim/hareketler'
      preLoaderRoute: typeof HesabimHareketlerRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/ilanlarim': {
      id: '/hesabim/ilanlarim'
      path: '/ilanlarim'
      fullPath: '/hesabim/ilanlarim'
      preLoaderRoute: typeof HesabimIlanlarimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/kayitli-arama': {
      id: '/hesabim/kayitli-arama'
      path: '/kayitli-arama'
      fullPath: '/hesabim/kayitli-arama'
      preLoaderRoute: typeof HesabimKayitliAramaRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/mesajlar': {
      id: '/hesabim/mesajlar'
      path: '/mesajlar'
      fullPath: '/hesabim/mesajlar'
      preLoaderRoute: typeof HesabimMesajlarRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/odemeler': {
      id: '/hesabim/odemeler'
      path: '/odemeler'
      fullPath: '/hesabim/odemeler'
      preLoaderRoute: typeof HesabimOdemelerRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/planim': {
      id: '/hesabim/planim'
      path: '/planim'
      fullPath: '/hesabim/planim'
      preLoaderRoute: typeof HesabimPlanimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/randevularim': {
      id: '/hesabim/randevularim'
      path: '/randevularim'
      fullPath: '/hesabim/randevularim'
      preLoaderRoute: typeof HesabimRandevularimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesap/askida': {
      id: '/hesap/askida'
      path: '/hesap/askida'
      fullPath: '/hesap/askida'
      preLoaderRoute: typeof HesapAskidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesap/dogrula': {
      id: '/hesap/dogrula'
      path: '/hesap/dogrula'
      fullPath: '/hesap/dogrula'
      preLoaderRoute: typeof HesapDogrulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$listingId': {
      id: '/ilan/$listingId'
      path: '/ilan/$listingId'
      fullPath: '/ilan/$listingId'
      preLoaderRoute: typeof IlanListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/hesap-var': {
      id: '/kayit_/hesap-var'
      path: '/kayit/hesap-var'
      fullPath: '/kayit/hesap-var'
      preLoaderRoute: typeof KayitHesapVarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/kurumsal': {
      id: '/kayit_/kurumsal'
      path: '/kayit/kurumsal'
      fullPath: '/kayit/kurumsal'
      preLoaderRoute: typeof KayitKurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/profil': {
      id: '/kayit_/profil'
      path: '/kayit/profil'
      fullPath: '/kayit/profil'
      preLoaderRoute: typeof KayitProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-sifirla_/gecersiz': {
      id: '/parola-sifirla_/gecersiz'
      path: '/parola-sifirla/gecersiz'
      fullPath: '/parola-sifirla/gecersiz'
      preLoaderRoute: typeof ParolaSifirlaGecersizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-sifirla_/gonderildi': {
      id: '/parola-sifirla_/gonderildi'
      path: '/parola-sifirla/gonderildi'
      fullPath: '/parola-sifirla/gonderildi'
      preLoaderRoute: typeof ParolaSifirlaGonderildiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-sifirla_/tamam': {
      id: '/parola-sifirla_/tamam'
      path: '/parola-sifirla/tamam'
      fullPath: '/parola-sifirla/tamam'
      preLoaderRoute: typeof ParolaSifirlaTamamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parola-sifirla_/yeni': {
      id: '/parola-sifirla_/yeni'
      path: '/parola-sifirla/yeni'
      fullPath: '/parola-sifirla/yeni'
      preLoaderRoute: typeof ParolaSifirlaYeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/google_/callback': {
      id: '/giris_/google_/callback'
      path: '/giris/google/callback'
      fullPath: '/giris/google/callback'
      preLoaderRoute: typeof GirisGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HesabimRouteChildren {
  HesabimFaturalarimRoute: typeof HesabimFaturalarimRoute
  HesabimGuvenlikRoute: typeof HesabimGuvenlikRoute
  HesabimHareketlerRoute: typeof HesabimHareketlerRoute
  HesabimIlanlarimRoute: typeof HesabimIlanlarimRoute
  HesabimKayitliAramaRoute: typeof HesabimKayitliAramaRoute
  HesabimMesajlarRoute: typeof HesabimMesajlarRoute
  HesabimOdemelerRoute: typeof HesabimOdemelerRoute
  HesabimPlanimRoute: typeof HesabimPlanimRoute
  HesabimRandevularimRoute: typeof HesabimRandevularimRoute
  HesabimIndexRoute: typeof HesabimIndexRoute
}

const HesabimRouteChildren: HesabimRouteChildren = {
  HesabimFaturalarimRoute: HesabimFaturalarimRoute,
  HesabimGuvenlikRoute: HesabimGuvenlikRoute,
  HesabimHareketlerRoute: HesabimHareketlerRoute,
  HesabimIlanlarimRoute: HesabimIlanlarimRoute,
  HesabimKayitliAramaRoute: HesabimKayitliAramaRoute,
  HesabimMesajlarRoute: HesabimMesajlarRoute,
  HesabimOdemelerRoute: HesabimOdemelerRoute,
  HesabimPlanimRoute: HesabimPlanimRoute,
  HesabimRandevularimRoute: HesabimRandevularimRoute,
  HesabimIndexRoute: HesabimIndexRoute,
}

const HesabimRouteWithChildren =
  HesabimRoute._addFileChildren(HesabimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDanismanRoute: AiDanismanRoute,
  ArsaAraRoute: ArsaAraRoute,
  BlogRoute: BlogRoute,
  BolgelerRoute: BolgelerRoute,
  EPostaDogrulaRoute: EPostaDogrulaRoute,
  EmlakRoute: EmlakRoute,
  FavorilerRoute: FavorilerRoute,
  GirisRoute: GirisRoute,
  HealthRoute: HealthRoute,
  HesabimRoute: HesabimRouteWithChildren,
  IlanVerRoute: IlanVerRoute,
  KarsilastirRoute: KarsilastirRoute,
  KayitRoute: KayitRoute,
  OfislerRoute: OfislerRoute,
  OrganizasyonSecRoute: OrganizasyonSecRoute,
  OturumSuresiDolduRoute: OturumSuresiDolduRoute,
  PaketlerRoute: PaketlerRoute,
  ParolaDegistirRoute: ParolaDegistirRoute,
  ParolaSifirlaRoute: ParolaSifirlaRoute,
  YetkisizRoute: YetkisizRoute,
  DavetTokenRoute: DavetTokenRoute,
  DavetGecersizRoute: DavetGecersizRoute,
  EmlakEndeksiSplatRoute: EmlakEndeksiSplatRoute,
  GirisHataRoute: GirisHataRoute,
  GirisKodRoute: GirisKodRoute,
  GirisParolaRoute: GirisParolaRoute,
  HesapAskidaRoute: HesapAskidaRoute,
  HesapDogrulaRoute: HesapDogrulaRoute,
  IlanListingIdRoute: IlanListingIdRoute,
  KayitHesapVarRoute: KayitHesapVarRoute,
  KayitKurumsalRoute: KayitKurumsalRoute,
  KayitProfilRoute: KayitProfilRoute,
  ParolaSifirlaGecersizRoute: ParolaSifirlaGecersizRoute,
  ParolaSifirlaGonderildiRoute: ParolaSifirlaGonderildiRoute,
  ParolaSifirlaTamamRoute: ParolaSifirlaTamamRoute,
  ParolaSifirlaYeniRoute: ParolaSifirlaYeniRoute,
  EmlakEndeksiIndexRoute: EmlakEndeksiIndexRoute,
  GirisGoogleCallbackRoute: GirisGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
