/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDanismanRouteImport } from './routes/ai-danisman'
import { Route as ArsaAraRouteImport } from './routes/arsa-ara'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BolgelerRouteImport } from './routes/bolgeler'
import { Route as EmlakRouteImport } from './routes/emlak'
import { Route as FavorilerRouteImport } from './routes/favoriler'
import { Route as GirisRouteImport } from './routes/giris'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HesabimRouteImport } from './routes/hesabim'
import { Route as IlanVerRouteImport } from './routes/ilan-ver'
import { Route as KarsilastirRouteImport } from './routes/karsilastir'
import { Route as KayitRouteImport } from './routes/kayit'
import { Route as OfislerRouteImport } from './routes/ofisler'
import { Route as GirisBaglantiGonderildiRouteImport } from './routes/giris_.baglanti-gonderildi'
import { Route as GirisHataRouteImport } from './routes/giris_.hata'
import { Route as GirisKodRouteImport } from './routes/giris_.kod'
import { Route as GirisParolaRouteImport } from './routes/giris_.parola'
import { Route as HesabimIndexRouteImport } from './routes/hesabim.index'
import { Route as HesabimFaturalarimRouteImport } from './routes/hesabim.faturalarim'
import { Route as HesabimGuvenlikRouteImport } from './routes/hesabim.guvenlik'
import { Route as HesabimHareketlerRouteImport } from './routes/hesabim.hareketler'
import { Route as HesabimIlanlarimRouteImport } from './routes/hesabim.ilanlarim'
import { Route as HesabimKayitliAramaRouteImport } from './routes/hesabim.kayitli-arama'
import { Route as HesabimMesajlarRouteImport } from './routes/hesabim.mesajlar'
import { Route as HesabimOdemelerRouteImport } from './routes/hesabim.odemeler'
import { Route as HesapDogrulaRouteImport } from './routes/hesap.dogrula'
import { Route as IlanListingIdRouteImport } from './routes/ilan.$listingId'
import { Route as KayitHesapVarRouteImport } from './routes/kayit_.hesap-var'
import { Route as KayitKurumsalRouteImport } from './routes/kayit_.kurumsal'
import { Route as KayitProfilRouteImport } from './routes/kayit_.profil'
import { Route as GirisBaglantiGecersizRouteImport } from './routes/giris_.baglanti_.gecersiz'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDanismanRoute = AiDanismanRouteImport.update({
  id: '/ai-danisman',
  path: '/ai-danisman',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsaAraRoute = ArsaAraRouteImport.update({
  id: '/arsa-ara',
  path: '/arsa-ara',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BolgelerRoute = BolgelerRouteImport.update({
  id: '/bolgeler',
  path: '/bolgeler',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakRoute = EmlakRouteImport.update({
  id: '/emlak',
  path: '/emlak',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorilerRoute = FavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisRoute = GirisRouteImport.update({
  id: '/giris',
  path: '/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimRoute = HesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanVerRoute = IlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const KarsilastirRoute = KarsilastirRouteImport.update({
  id: '/karsilastir',
  path: '/karsilastir',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitRoute = KayitRouteImport.update({
  id: '/kayit',
  path: '/kayit',
  getParentRoute: () => rootRouteImport,
} as any)
const OfislerRoute = OfislerRouteImport.update({
  id: '/ofisler',
  path: '/ofisler',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisBaglantiGonderildiRoute = GirisBaglantiGonderildiRouteImport.update({
  id: '/giris_/baglanti-gonderildi',
  path: '/giris/baglanti-gonderildi',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisHataRoute = GirisHataRouteImport.update({
  id: '/giris_/hata',
  path: '/giris/hata',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisKodRoute = GirisKodRouteImport.update({
  id: '/giris_/kod',
  path: '/giris/kod',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisParolaRoute = GirisParolaRouteImport.update({
  id: '/giris_/parola',
  path: '/giris/parola',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimIndexRoute = HesabimIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimFaturalarimRoute = HesabimFaturalarimRouteImport.update({
  id: '/faturalarim',
  path: '/faturalarim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimGuvenlikRoute = HesabimGuvenlikRouteImport.update({
  id: '/guvenlik',
  path: '/guvenlik',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimHareketlerRoute = HesabimHareketlerRouteImport.update({
  id: '/hareketler',
  path: '/hareketler',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimIlanlarimRoute = HesabimIlanlarimRouteImport.update({
  id: '/ilanlarim',
  path: '/ilanlarim',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimKayitliAramaRoute = HesabimKayitliAramaRouteImport.update({
  id: '/kayitli-arama',
  path: '/kayitli-arama',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimMesajlarRoute = HesabimMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => HesabimRoute,
} as any)
const HesabimOdemelerRoute = HesabimOdemelerRouteImport.update({
  id: '/odemeler',
  path: '/odemeler',
  getParentRoute: () => HesabimRoute,
} as any)
const HesapDogrulaRoute = HesapDogrulaRouteImport.update({
  id: '/hesap/dogrula',
  path: '/hesap/dogrula',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanListingIdRoute = IlanListingIdRouteImport.update({
  id: '/ilan/$listingId',
  path: '/ilan/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitHesapVarRoute = KayitHesapVarRouteImport.update({
  id: '/kayit_/hesap-var',
  path: '/kayit/hesap-var',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitKurumsalRoute = KayitKurumsalRouteImport.update({
  id: '/kayit_/kurumsal',
  path: '/kayit/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const KayitProfilRoute = KayitProfilRouteImport.update({
  id: '/kayit_/profil',
  path: '/kayit/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const GirisBaglantiGecersizRoute = GirisBaglantiGecersizRouteImport.update({
  id: '/giris_/baglanti_/gecersiz',
  path: '/giris/baglanti/gecersiz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRouteWithChildren
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/giris/baglanti-gonderildi': typeof GirisBaglantiGonderildiRoute
  '/giris/hata': typeof GirisHataRoute
  '/giris/kod': typeof GirisKodRoute
  '/giris/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit/hesap-var': typeof KayitHesapVarRoute
  '/kayit/kurumsal': typeof KayitKurumsalRoute
  '/kayit/profil': typeof KayitProfilRoute
  '/hesabim/': typeof HesabimIndexRoute
  '/giris/baglanti/gecersiz': typeof GirisBaglantiGecersizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/giris/baglanti-gonderildi': typeof GirisBaglantiGonderildiRoute
  '/giris/hata': typeof GirisHataRoute
  '/giris/kod': typeof GirisKodRoute
  '/giris/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit/hesap-var': typeof KayitHesapVarRoute
  '/kayit/kurumsal': typeof KayitKurumsalRoute
  '/kayit/profil': typeof KayitProfilRoute
  '/hesabim': typeof HesabimIndexRoute
  '/giris/baglanti/gecersiz': typeof GirisBaglantiGecersizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/giris': typeof GirisRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRouteWithChildren
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/kayit': typeof KayitRoute
  '/ofisler': typeof OfislerRoute
  '/giris_/baglanti-gonderildi': typeof GirisBaglantiGonderildiRoute
  '/giris_/hata': typeof GirisHataRoute
  '/giris_/kod': typeof GirisKodRoute
  '/giris_/parola': typeof GirisParolaRoute
  '/hesabim/faturalarim': typeof HesabimFaturalarimRoute
  '/hesabim/guvenlik': typeof HesabimGuvenlikRoute
  '/hesabim/hareketler': typeof HesabimHareketlerRoute
  '/hesabim/ilanlarim': typeof HesabimIlanlarimRoute
  '/hesabim/kayitli-arama': typeof HesabimKayitliAramaRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/hesabim/odemeler': typeof HesabimOdemelerRoute
  '/hesap/dogrula': typeof HesapDogrulaRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/kayit_/hesap-var': typeof KayitHesapVarRoute
  '/kayit_/kurumsal': typeof KayitKurumsalRoute
  '/kayit_/profil': typeof KayitProfilRoute
  '/hesabim/': typeof HesabimIndexRoute
  '/giris_/baglanti_/gecersiz': typeof GirisBaglantiGecersizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/giris/baglanti-gonderildi'
    | '/giris/hata'
    | '/giris/kod'
    | '/giris/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit/hesap-var'
    | '/kayit/kurumsal'
    | '/kayit/profil'
    | '/hesabim/'
    | '/giris/baglanti/gecersiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/giris/baglanti-gonderildi'
    | '/giris/hata'
    | '/giris/kod'
    | '/giris/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit/hesap-var'
    | '/kayit/kurumsal'
    | '/kayit/profil'
    | '/hesabim'
    | '/giris/baglanti/gecersiz'
  id:
    | '__root__'
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/giris'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/kayit'
    | '/ofisler'
    | '/giris_/baglanti-gonderildi'
    | '/giris_/hata'
    | '/giris_/kod'
    | '/giris_/parola'
    | '/hesabim/faturalarim'
    | '/hesabim/guvenlik'
    | '/hesabim/hareketler'
    | '/hesabim/ilanlarim'
    | '/hesabim/kayitli-arama'
    | '/hesabim/mesajlar'
    | '/hesabim/odemeler'
    | '/hesap/dogrula'
    | '/ilan/$listingId'
    | '/kayit_/hesap-var'
    | '/kayit_/kurumsal'
    | '/kayit_/profil'
    | '/hesabim/'
    | '/giris_/baglanti_/gecersiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDanismanRoute: typeof AiDanismanRoute
  ArsaAraRoute: typeof ArsaAraRoute
  BlogRoute: typeof BlogRoute
  BolgelerRoute: typeof BolgelerRoute
  EmlakRoute: typeof EmlakRoute
  FavorilerRoute: typeof FavorilerRoute
  GirisRoute: typeof GirisRoute
  HealthRoute: typeof HealthRoute
  HesabimRoute: typeof HesabimRouteWithChildren
  IlanVerRoute: typeof IlanVerRoute
  KarsilastirRoute: typeof KarsilastirRoute
  KayitRoute: typeof KayitRoute
  OfislerRoute: typeof OfislerRoute
  GirisBaglantiGonderildiRoute: typeof GirisBaglantiGonderildiRoute
  GirisHataRoute: typeof GirisHataRoute
  GirisKodRoute: typeof GirisKodRoute
  GirisParolaRoute: typeof GirisParolaRoute
  HesapDogrulaRoute: typeof HesapDogrulaRoute
  IlanListingIdRoute: typeof IlanListingIdRoute
  KayitHesapVarRoute: typeof KayitHesapVarRoute
  KayitKurumsalRoute: typeof KayitKurumsalRoute
  KayitProfilRoute: typeof KayitProfilRoute
  GirisBaglantiGecersizRoute: typeof GirisBaglantiGecersizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-danisman': {
      id: '/ai-danisman'
      path: '/ai-danisman'
      fullPath: '/ai-danisman'
      preLoaderRoute: typeof AiDanismanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsa-ara': {
      id: '/arsa-ara'
      path: '/arsa-ara'
      fullPath: '/arsa-ara'
      preLoaderRoute: typeof ArsaAraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolgeler': {
      id: '/bolgeler'
      path: '/bolgeler'
      fullPath: '/bolgeler'
      preLoaderRoute: typeof BolgelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak': {
      id: '/emlak'
      path: '/emlak'
      fullPath: '/emlak'
      preLoaderRoute: typeof EmlakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriler': {
      id: '/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof FavorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris': {
      id: '/giris'
      path: '/giris'
      fullPath: '/giris'
      preLoaderRoute: typeof GirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim': {
      id: '/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof HesabimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan-ver': {
      id: '/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof IlanVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karsilastir': {
      id: '/karsilastir'
      path: '/karsilastir'
      fullPath: '/karsilastir'
      preLoaderRoute: typeof KarsilastirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit': {
      id: '/kayit'
      path: '/kayit'
      fullPath: '/kayit'
      preLoaderRoute: typeof KayitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofisler': {
      id: '/ofisler'
      path: '/ofisler'
      fullPath: '/ofisler'
      preLoaderRoute: typeof OfislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/baglanti-gonderildi': {
      id: '/giris_/baglanti-gonderildi'
      path: '/giris/baglanti-gonderildi'
      fullPath: '/giris/baglanti-gonderildi'
      preLoaderRoute: typeof GirisBaglantiGonderildiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/hata': {
      id: '/giris_/hata'
      path: '/giris/hata'
      fullPath: '/giris/hata'
      preLoaderRoute: typeof GirisHataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/kod': {
      id: '/giris_/kod'
      path: '/giris/kod'
      fullPath: '/giris/kod'
      preLoaderRoute: typeof GirisKodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/parola': {
      id: '/giris_/parola'
      path: '/giris/parola'
      fullPath: '/giris/parola'
      preLoaderRoute: typeof GirisParolaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim/': {
      id: '/hesabim/'
      path: '/'
      fullPath: '/hesabim/'
      preLoaderRoute: typeof HesabimIndexRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/faturalarim': {
      id: '/hesabim/faturalarim'
      path: '/faturalarim'
      fullPath: '/hesabim/faturalarim'
      preLoaderRoute: typeof HesabimFaturalarimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/guvenlik': {
      id: '/hesabim/guvenlik'
      path: '/guvenlik'
      fullPath: '/hesabim/guvenlik'
      preLoaderRoute: typeof HesabimGuvenlikRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/hareketler': {
      id: '/hesabim/hareketler'
      path: '/hareketler'
      fullPath: '/hesabim/hareketler'
      preLoaderRoute: typeof HesabimHareketlerRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/ilanlarim': {
      id: '/hesabim/ilanlarim'
      path: '/ilanlarim'
      fullPath: '/hesabim/ilanlarim'
      preLoaderRoute: typeof HesabimIlanlarimRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/kayitli-arama': {
      id: '/hesabim/kayitli-arama'
      path: '/kayitli-arama'
      fullPath: '/hesabim/kayitli-arama'
      preLoaderRoute: typeof HesabimKayitliAramaRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/mesajlar': {
      id: '/hesabim/mesajlar'
      path: '/mesajlar'
      fullPath: '/hesabim/mesajlar'
      preLoaderRoute: typeof HesabimMesajlarRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesabim/odemeler': {
      id: '/hesabim/odemeler'
      path: '/odemeler'
      fullPath: '/hesabim/odemeler'
      preLoaderRoute: typeof HesabimOdemelerRouteImport
      parentRoute: typeof HesabimRoute
    }
    '/hesap/dogrula': {
      id: '/hesap/dogrula'
      path: '/hesap/dogrula'
      fullPath: '/hesap/dogrula'
      preLoaderRoute: typeof HesapDogrulaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$listingId': {
      id: '/ilan/$listingId'
      path: '/ilan/$listingId'
      fullPath: '/ilan/$listingId'
      preLoaderRoute: typeof IlanListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/hesap-var': {
      id: '/kayit_/hesap-var'
      path: '/kayit/hesap-var'
      fullPath: '/kayit/hesap-var'
      preLoaderRoute: typeof KayitHesapVarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/kurumsal': {
      id: '/kayit_/kurumsal'
      path: '/kayit/kurumsal'
      fullPath: '/kayit/kurumsal'
      preLoaderRoute: typeof KayitKurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayit_/profil': {
      id: '/kayit_/profil'
      path: '/kayit/profil'
      fullPath: '/kayit/profil'
      preLoaderRoute: typeof KayitProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giris_/baglanti_/gecersiz': {
      id: '/giris_/baglanti_/gecersiz'
      path: '/giris/baglanti/gecersiz'
      fullPath: '/giris/baglanti/gecersiz'
      preLoaderRoute: typeof GirisBaglantiGecersizRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HesabimRouteChildren {
  HesabimFaturalarimRoute: typeof HesabimFaturalarimRoute
  HesabimGuvenlikRoute: typeof HesabimGuvenlikRoute
  HesabimHareketlerRoute: typeof HesabimHareketlerRoute
  HesabimIlanlarimRoute: typeof HesabimIlanlarimRoute
  HesabimKayitliAramaRoute: typeof HesabimKayitliAramaRoute
  HesabimMesajlarRoute: typeof HesabimMesajlarRoute
  HesabimOdemelerRoute: typeof HesabimOdemelerRoute
  HesabimIndexRoute: typeof HesabimIndexRoute
}

const HesabimRouteChildren: HesabimRouteChildren = {
  HesabimFaturalarimRoute: HesabimFaturalarimRoute,
  HesabimGuvenlikRoute: HesabimGuvenlikRoute,
  HesabimHareketlerRoute: HesabimHareketlerRoute,
  HesabimIlanlarimRoute: HesabimIlanlarimRoute,
  HesabimKayitliAramaRoute: HesabimKayitliAramaRoute,
  HesabimMesajlarRoute: HesabimMesajlarRoute,
  HesabimOdemelerRoute: HesabimOdemelerRoute,
  HesabimIndexRoute: HesabimIndexRoute,
}

const HesabimRouteWithChildren =
  HesabimRoute._addFileChildren(HesabimRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDanismanRoute: AiDanismanRoute,
  ArsaAraRoute: ArsaAraRoute,
  BlogRoute: BlogRoute,
  BolgelerRoute: BolgelerRoute,
  EmlakRoute: EmlakRoute,
  FavorilerRoute: FavorilerRoute,
  GirisRoute: GirisRoute,
  HealthRoute: HealthRoute,
  HesabimRoute: HesabimRouteWithChildren,
  IlanVerRoute: IlanVerRoute,
  KarsilastirRoute: KarsilastirRoute,
  KayitRoute: KayitRoute,
  OfislerRoute: OfislerRoute,
  GirisBaglantiGonderildiRoute: GirisBaglantiGonderildiRoute,
  GirisHataRoute: GirisHataRoute,
  GirisKodRoute: GirisKodRoute,
  GirisParolaRoute: GirisParolaRoute,
  HesapDogrulaRoute: HesapDogrulaRoute,
  IlanListingIdRoute: IlanListingIdRoute,
  KayitHesapVarRoute: KayitHesapVarRoute,
  KayitKurumsalRoute: KayitKurumsalRoute,
  KayitProfilRoute: KayitProfilRoute,
  GirisBaglantiGecersizRoute: GirisBaglantiGecersizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
