/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDanismanRouteImport } from './routes/ai-danisman'
import { Route as ArsaAraRouteImport } from './routes/arsa-ara'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BolgelerRouteImport } from './routes/bolgeler'
import { Route as EmlakRouteImport } from './routes/emlak'
import { Route as FavorilerRouteImport } from './routes/favoriler'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HesabimRouteImport } from './routes/hesabim'
import { Route as IlanVerRouteImport } from './routes/ilan-ver'
import { Route as KarsilastirRouteImport } from './routes/karsilastir'
import { Route as KonseptlerRouteImport } from './routes/konseptler'
import { Route as OfislerRouteImport } from './routes/ofisler'
import { Route as HesabimMesajlarRouteImport } from './routes/hesabim_.mesajlar'
import { Route as IlanListingIdRouteImport } from './routes/ilan.$listingId'
import { Route as KonseptlerIndexRouteImport } from './routes/konseptler.index'
import { Route as KonseptlerAiDanismanRouteImport } from './routes/konseptler.ai-danisman'
import { Route as KonseptlerAiKesifRouteImport } from './routes/konseptler.ai-kesif'
import { Route as KonseptlerGuvenMerkeziRouteImport } from './routes/konseptler.guven-merkezi'
import { Route as KonseptlerHaritaKesfiRouteImport } from './routes/konseptler.harita-kesfi'
import { Route as KonseptlerPazarVitriniRouteImport } from './routes/konseptler.pazar-vitrini'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDanismanRoute = AiDanismanRouteImport.update({
  id: '/ai-danisman',
  path: '/ai-danisman',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsaAraRoute = ArsaAraRouteImport.update({
  id: '/arsa-ara',
  path: '/arsa-ara',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BolgelerRoute = BolgelerRouteImport.update({
  id: '/bolgeler',
  path: '/bolgeler',
  getParentRoute: () => rootRouteImport,
} as any)
const EmlakRoute = EmlakRouteImport.update({
  id: '/emlak',
  path: '/emlak',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorilerRoute = FavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimRoute = HesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanVerRoute = IlanVerRouteImport.update({
  id: '/ilan-ver',
  path: '/ilan-ver',
  getParentRoute: () => rootRouteImport,
} as any)
const KarsilastirRoute = KarsilastirRouteImport.update({
  id: '/karsilastir',
  path: '/karsilastir',
  getParentRoute: () => rootRouteImport,
} as any)
const KonseptlerRoute = KonseptlerRouteImport.update({
  id: '/konseptler',
  path: '/konseptler',
  getParentRoute: () => rootRouteImport,
} as any)
const OfislerRoute = OfislerRouteImport.update({
  id: '/ofisler',
  path: '/ofisler',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimMesajlarRoute = HesabimMesajlarRouteImport.update({
  id: '/hesabim_/mesajlar',
  path: '/hesabim/mesajlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IlanListingIdRoute = IlanListingIdRouteImport.update({
  id: '/ilan/$listingId',
  path: '/ilan/$listingId',
  getParentRoute: () => rootRouteImport,
} as any)
const KonseptlerIndexRoute = KonseptlerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KonseptlerRoute,
} as any)
const KonseptlerAiDanismanRoute = KonseptlerAiDanismanRouteImport.update({
  id: '/ai-danisman',
  path: '/ai-danisman',
  getParentRoute: () => KonseptlerRoute,
} as any)
const KonseptlerAiKesifRoute = KonseptlerAiKesifRouteImport.update({
  id: '/ai-kesif',
  path: '/ai-kesif',
  getParentRoute: () => KonseptlerRoute,
} as any)
const KonseptlerGuvenMerkeziRoute = KonseptlerGuvenMerkeziRouteImport.update({
  id: '/guven-merkezi',
  path: '/guven-merkezi',
  getParentRoute: () => KonseptlerRoute,
} as any)
const KonseptlerHaritaKesfiRoute = KonseptlerHaritaKesfiRouteImport.update({
  id: '/harita-kesfi',
  path: '/harita-kesfi',
  getParentRoute: () => KonseptlerRoute,
} as any)
const KonseptlerPazarVitriniRoute = KonseptlerPazarVitriniRouteImport.update({
  id: '/pazar-vitrini',
  path: '/pazar-vitrini',
  getParentRoute: () => KonseptlerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRoute
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/konseptler': typeof KonseptlerRouteWithChildren
  '/ofisler': typeof OfislerRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/konseptler/ai-danisman': typeof KonseptlerAiDanismanRoute
  '/konseptler/ai-kesif': typeof KonseptlerAiKesifRoute
  '/konseptler/guven-merkezi': typeof KonseptlerGuvenMerkeziRoute
  '/konseptler/harita-kesfi': typeof KonseptlerHaritaKesfiRoute
  '/konseptler/pazar-vitrini': typeof KonseptlerPazarVitriniRoute
  '/konseptler/': typeof KonseptlerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRoute
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/ofisler': typeof OfislerRoute
  '/hesabim/mesajlar': typeof HesabimMesajlarRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/konseptler/ai-danisman': typeof KonseptlerAiDanismanRoute
  '/konseptler/ai-kesif': typeof KonseptlerAiKesifRoute
  '/konseptler/guven-merkezi': typeof KonseptlerGuvenMerkeziRoute
  '/konseptler/harita-kesfi': typeof KonseptlerHaritaKesfiRoute
  '/konseptler/pazar-vitrini': typeof KonseptlerPazarVitriniRoute
  '/konseptler': typeof KonseptlerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-danisman': typeof AiDanismanRoute
  '/arsa-ara': typeof ArsaAraRoute
  '/blog': typeof BlogRoute
  '/bolgeler': typeof BolgelerRoute
  '/emlak': typeof EmlakRoute
  '/favoriler': typeof FavorilerRoute
  '/health': typeof HealthRoute
  '/hesabim': typeof HesabimRoute
  '/ilan-ver': typeof IlanVerRoute
  '/karsilastir': typeof KarsilastirRoute
  '/konseptler': typeof KonseptlerRouteWithChildren
  '/ofisler': typeof OfislerRoute
  '/hesabim_/mesajlar': typeof HesabimMesajlarRoute
  '/ilan/$listingId': typeof IlanListingIdRoute
  '/konseptler/ai-danisman': typeof KonseptlerAiDanismanRoute
  '/konseptler/ai-kesif': typeof KonseptlerAiKesifRoute
  '/konseptler/guven-merkezi': typeof KonseptlerGuvenMerkeziRoute
  '/konseptler/harita-kesfi': typeof KonseptlerHaritaKesfiRoute
  '/konseptler/pazar-vitrini': typeof KonseptlerPazarVitriniRoute
  '/konseptler/': typeof KonseptlerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/konseptler'
    | '/ofisler'
    | '/hesabim/mesajlar'
    | '/ilan/$listingId'
    | '/konseptler/ai-danisman'
    | '/konseptler/ai-kesif'
    | '/konseptler/guven-merkezi'
    | '/konseptler/harita-kesfi'
    | '/konseptler/pazar-vitrini'
    | '/konseptler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/ofisler'
    | '/hesabim/mesajlar'
    | '/ilan/$listingId'
    | '/konseptler/ai-danisman'
    | '/konseptler/ai-kesif'
    | '/konseptler/guven-merkezi'
    | '/konseptler/harita-kesfi'
    | '/konseptler/pazar-vitrini'
    | '/konseptler'
  id:
    | '__root__'
    | '/'
    | '/ai-danisman'
    | '/arsa-ara'
    | '/blog'
    | '/bolgeler'
    | '/emlak'
    | '/favoriler'
    | '/health'
    | '/hesabim'
    | '/ilan-ver'
    | '/karsilastir'
    | '/konseptler'
    | '/ofisler'
    | '/hesabim_/mesajlar'
    | '/ilan/$listingId'
    | '/konseptler/ai-danisman'
    | '/konseptler/ai-kesif'
    | '/konseptler/guven-merkezi'
    | '/konseptler/harita-kesfi'
    | '/konseptler/pazar-vitrini'
    | '/konseptler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDanismanRoute: typeof AiDanismanRoute
  ArsaAraRoute: typeof ArsaAraRoute
  BlogRoute: typeof BlogRoute
  BolgelerRoute: typeof BolgelerRoute
  EmlakRoute: typeof EmlakRoute
  FavorilerRoute: typeof FavorilerRoute
  HealthRoute: typeof HealthRoute
  HesabimRoute: typeof HesabimRoute
  IlanVerRoute: typeof IlanVerRoute
  KarsilastirRoute: typeof KarsilastirRoute
  KonseptlerRoute: typeof KonseptlerRouteWithChildren
  OfislerRoute: typeof OfislerRoute
  HesabimMesajlarRoute: typeof HesabimMesajlarRoute
  IlanListingIdRoute: typeof IlanListingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-danisman': {
      id: '/ai-danisman'
      path: '/ai-danisman'
      fullPath: '/ai-danisman'
      preLoaderRoute: typeof AiDanismanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsa-ara': {
      id: '/arsa-ara'
      path: '/arsa-ara'
      fullPath: '/arsa-ara'
      preLoaderRoute: typeof ArsaAraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolgeler': {
      id: '/bolgeler'
      path: '/bolgeler'
      fullPath: '/bolgeler'
      preLoaderRoute: typeof BolgelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emlak': {
      id: '/emlak'
      path: '/emlak'
      fullPath: '/emlak'
      preLoaderRoute: typeof EmlakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriler': {
      id: '/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof FavorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim': {
      id: '/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof HesabimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan-ver': {
      id: '/ilan-ver'
      path: '/ilan-ver'
      fullPath: '/ilan-ver'
      preLoaderRoute: typeof IlanVerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karsilastir': {
      id: '/karsilastir'
      path: '/karsilastir'
      fullPath: '/karsilastir'
      preLoaderRoute: typeof KarsilastirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konseptler': {
      id: '/konseptler'
      path: '/konseptler'
      fullPath: '/konseptler'
      preLoaderRoute: typeof KonseptlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofisler': {
      id: '/ofisler'
      path: '/ofisler'
      fullPath: '/ofisler'
      preLoaderRoute: typeof OfislerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim_/mesajlar': {
      id: '/hesabim_/mesajlar'
      path: '/hesabim/mesajlar'
      fullPath: '/hesabim/mesajlar'
      preLoaderRoute: typeof HesabimMesajlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilan/$listingId': {
      id: '/ilan/$listingId'
      path: '/ilan/$listingId'
      fullPath: '/ilan/$listingId'
      preLoaderRoute: typeof IlanListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konseptler/': {
      id: '/konseptler/'
      path: '/'
      fullPath: '/konseptler/'
      preLoaderRoute: typeof KonseptlerIndexRouteImport
      parentRoute: typeof KonseptlerRoute
    }
    '/konseptler/ai-danisman': {
      id: '/konseptler/ai-danisman'
      path: '/ai-danisman'
      fullPath: '/konseptler/ai-danisman'
      preLoaderRoute: typeof KonseptlerAiDanismanRouteImport
      parentRoute: typeof KonseptlerRoute
    }
    '/konseptler/ai-kesif': {
      id: '/konseptler/ai-kesif'
      path: '/ai-kesif'
      fullPath: '/konseptler/ai-kesif'
      preLoaderRoute: typeof KonseptlerAiKesifRouteImport
      parentRoute: typeof KonseptlerRoute
    }
    '/konseptler/guven-merkezi': {
      id: '/konseptler/guven-merkezi'
      path: '/guven-merkezi'
      fullPath: '/konseptler/guven-merkezi'
      preLoaderRoute: typeof KonseptlerGuvenMerkeziRouteImport
      parentRoute: typeof KonseptlerRoute
    }
    '/konseptler/harita-kesfi': {
      id: '/konseptler/harita-kesfi'
      path: '/harita-kesfi'
      fullPath: '/konseptler/harita-kesfi'
      preLoaderRoute: typeof KonseptlerHaritaKesfiRouteImport
      parentRoute: typeof KonseptlerRoute
    }
    '/konseptler/pazar-vitrini': {
      id: '/konseptler/pazar-vitrini'
      path: '/pazar-vitrini'
      fullPath: '/konseptler/pazar-vitrini'
      preLoaderRoute: typeof KonseptlerPazarVitriniRouteImport
      parentRoute: typeof KonseptlerRoute
    }
  }
}

interface KonseptlerRouteChildren {
  KonseptlerAiDanismanRoute: typeof KonseptlerAiDanismanRoute
  KonseptlerAiKesifRoute: typeof KonseptlerAiKesifRoute
  KonseptlerGuvenMerkeziRoute: typeof KonseptlerGuvenMerkeziRoute
  KonseptlerHaritaKesfiRoute: typeof KonseptlerHaritaKesfiRoute
  KonseptlerPazarVitriniRoute: typeof KonseptlerPazarVitriniRoute
  KonseptlerIndexRoute: typeof KonseptlerIndexRoute
}

const KonseptlerRouteChildren: KonseptlerRouteChildren = {
  KonseptlerAiDanismanRoute: KonseptlerAiDanismanRoute,
  KonseptlerAiKesifRoute: KonseptlerAiKesifRoute,
  KonseptlerGuvenMerkeziRoute: KonseptlerGuvenMerkeziRoute,
  KonseptlerHaritaKesfiRoute: KonseptlerHaritaKesfiRoute,
  KonseptlerPazarVitriniRoute: KonseptlerPazarVitriniRoute,
  KonseptlerIndexRoute: KonseptlerIndexRoute,
}

const KonseptlerRouteWithChildren = KonseptlerRoute._addFileChildren(
  KonseptlerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDanismanRoute: AiDanismanRoute,
  ArsaAraRoute: ArsaAraRoute,
  BlogRoute: BlogRoute,
  BolgelerRoute: BolgelerRoute,
  EmlakRoute: EmlakRoute,
  FavorilerRoute: FavorilerRoute,
  HealthRoute: HealthRoute,
  HesabimRoute: HesabimRoute,
  IlanVerRoute: IlanVerRoute,
  KarsilastirRoute: KarsilastirRoute,
  KonseptlerRoute: KonseptlerRouteWithChildren,
  OfislerRoute: OfislerRoute,
  HesabimMesajlarRoute: HesabimMesajlarRoute,
  IlanListingIdRoute: IlanListingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
